### ISSUE TITLE
Empty input instead of showing previous task

### ISSUE THREAD

**Issue by veredrec** [facn2/Week2-Ba6e5-Developers-TodoList#35]
After writing a new task, it might be nice to "clear" the input area or have the placeholder back there, instead of the previous message - which you can't submit again but is still there.

**Comment by mattlub** [comment]
👍

**Comment by Heathercoraje** [comment]
@veredrec fixed! Have a look and please close the issue, heart

**Comment by veredrec** [comment]
We forgot as well but the mentors mentioned that we need to write the pull request number for this issue :)
